name: Build LaTeX PDF

on:
  push:
    paths:
      - 'documentation/**'  
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: documentation/main.tex    

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: documentation/main.pdf
