name: Build all LaTeX PDFs

on:
  push:
    paths:
      - '**/*.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build PDFs for all .tex files
      run: |
        mkdir -p built_pdfs
        tex_files=$(find . -name '*.tex')
        for texfile in $tex_files; do
          dir=$(dirname "$texfile")
          base=$(basename "$texfile" .tex)
          pushd "$dir"
          pdflatex -interaction=nonstopmode "$base.tex"
          pdflatex -interaction=nonstopmode "$base.tex"
          mv "$base.pdf" ../../built_pdfs/"${dir//\//_}__$base.pdf"
          popd
        done

    - name: Upload PDFs
      uses: actions/upload-artifact@v4
      with:
        name: PDFs
        path: built_pdfs/*.pdf
